-- ============================================================================
--  Phase 4 — Listings Engine
--
--  · properties gain the identity they never had, so a re-list or a second
--    provider updates one house instead of creating a second one
--  · a refresh is a diff: new / price change / removed / relisted / unchanged,
--    each with an audit row and a price-history entry
--  · v_listings_enriched carries listing + property + latest eligibility so the
--    All Listings page filters and sorts in the database
--
--  Run in Supabase SQL Editor after 0004. Idempotent.
-- ============================================================================

-- ───────────────────────── property identity ────────────────────────────────
alter table properties add column if not exists unit text;

-- Phase 1 inserted a fresh properties row for every listing it had not seen
-- before, with no lookup and no constraint. The same house arriving from a
-- second provider, or re-listed under a new MLS number, became a second
-- property — splitting its notes, pipeline status and eligibility history.
-- Merge any such rows onto the lowest id, then make it impossible again.
do $$
declare v_dupes int;
begin
  drop table if exists _property_merge;
  create unlogged table _property_merge as
    select p.id as dupe_id,
           min(p.id) over (partition by p.market_id, p.address_norm, coalesce(p.unit, '')) as keeper_id
      from properties p
     where p.address_norm is not null;
  delete from _property_merge where dupe_id = keeper_id;

  select count(*) into v_dupes from _property_merge;
  if v_dupes = 0 then
    raise notice 'No duplicate properties to merge.';
  else
    raise notice 'Merging % duplicate properties onto their earliest row.', v_dupes;

    -- user-owned rows move to the keeper; drop the loser where the keeper
    -- already has one, since these tables are unique per property (or per user)
    delete from saved_properties s using _property_merge m
     where s.property_id = m.dupe_id
       and exists (select 1 from saved_properties k where k.property_id = m.keeper_id and k.user_id = s.user_id);
    update saved_properties s set property_id = m.keeper_id from _property_merge m where s.property_id = m.dupe_id;

    delete from acquisition_pipeline a using _property_merge m
     where a.property_id = m.dupe_id
       and exists (select 1 from acquisition_pipeline k where k.property_id = m.keeper_id);
    update acquisition_pipeline a set property_id = m.keeper_id from _property_merge m where a.property_id = m.dupe_id;

    delete from property_features f using _property_merge m
     where f.property_id = m.dupe_id
       and exists (select 1 from property_features k where k.property_id = m.keeper_id and k.feature_key = f.feature_key);
    update property_features f set property_id = m.keeper_id from _property_merge m where f.property_id = m.dupe_id;

    update property_notes n    set property_id = m.keeper_id from _property_merge m where n.property_id = m.dupe_id;
    update hoa_verifications h set property_id = m.keeper_id from _property_merge m where h.property_id = m.dupe_id;
    update listings l          set property_id = m.keeper_id from _property_merge m where l.property_id = m.dupe_id;

    -- everything else hanging off a property is derived and regenerated by a
    -- re-run, so let the cascade take it
    delete from properties p using _property_merge m where p.id = m.dupe_id;
  end if;
  drop table if exists _property_merge;
end $$;

create unique index if not exists properties_identity_uniq
  on properties (market_id, address_norm, coalesce(unit, ''))
  where address_norm is not null;
create index if not exists properties_addr_norm_idx on properties(market_id, address_norm);

/**
 * Find the property a listing belongs to: canonical address first, then a
 * coordinate match inside a tolerance, so a provider that spells the address
 * differently does not create a second house.
 * Returns null when there is genuinely no match — the caller then inserts.
 */
create or replace function fn_match_property(
  p_market text, p_address_norm text, p_unit text,
  p_lat double precision, p_lng double precision, p_tolerance_ft numeric default 60)
returns bigint language plpgsql stable as $$
declare v_id bigint; srid int;
begin
  select id into v_id from properties
   where market_id = p_market and address_norm = p_address_norm
     and coalesce(unit, '') = coalesce(p_unit, '')
   limit 1;
  if v_id is not null then return v_id; end if;

  if p_lat is null or p_lng is null then return null; end if;
  select m.srid_feet into srid from markets m where m.id = p_market;
  if srid is null then return null; end if;

  select p.id into v_id
    from properties p
   where p.market_id = p_market and p.geom is not null
     and coalesce(p.unit, '') = coalesce(p_unit, '')
     and ST_DWithin(ST_Transform(p.geom, srid),
                    ST_Transform(ST_SetSRID(ST_MakePoint(p_lng, p_lat), 4326), srid),
                    p_tolerance_ft)
   order by ST_Distance(ST_Transform(p.geom, srid),
                        ST_Transform(ST_SetSRID(ST_MakePoint(p_lng, p_lat), 4326), srid))
   limit 1;
  return v_id;
end $$;

-- ───────────────────────── refresh audit ────────────────────────────────────
alter table listing_refreshes add column if not exists unchanged  int default 0;
alter table listing_refreshes add column if not exists relisted   int default 0;
alter table listing_refreshes add column if not exists received   int default 0;
alter table listing_refreshes add column if not exists full_sync  boolean default false;
alter table listing_refreshes add column if not exists rescreened int default 0;
alter table listing_refreshes add column if not exists actor_note text;

alter table listings add column if not exists previous_price bigint;
alter table listings add column if not exists price_changed_at timestamptz;
create index if not exists listings_property_idx on listings(property_id);
create index if not exists listings_price_idx on listings(market_id, list_price);

-- ───────────────────────── the All Listings source ──────────────────────────
-- One row per listing carrying its property and its latest eligibility, so the
-- page can filter and sort in the database rather than pulling everything.
drop view if exists v_listings_enriched;
create view v_listings_enriched with (security_invoker = true) as
  select
    l.id                        as listing_id,
    l.market_id, l.provider, l.external_id, l.status,
    l.list_price, l.original_price, l.previous_price, l.price_changed_at,
    l.days_on_market, l.listed_at, l.url, l.primary_photo, l.brokerage, l.agent,
    l.first_seen, l.last_seen, l.removed_at,
    case when l.original_price is not null and l.original_price > 0 and l.list_price is not null
         then round(((l.original_price - l.list_price)::numeric / l.original_price) * 100, 1) end as price_drop_pct,
    (l.original_price - l.list_price)                                                             as price_drop,
    p.id                        as property_id,
    p.address, p.address_norm, p.unit, p.zip, p.lat, p.lng,
    p.beds, p.baths, p.sqft, p.lot_sqft, p.year_built, p.property_type, p.stories,
    p.garage, p.pool, p.basement, p.finished_basement,
    p.hoa_status, p.hoa_fee_monthly, p.hoa_name,
    p.parcel_id, p.parcel_match_confidence,
    case when p.sqft is not null and p.sqft > 0 and l.list_price is not null
         then round(l.list_price::numeric / p.sqft, 0) end                                        as price_per_sqft,
    e.classification, e.summary as eligibility_summary,
    e.zone_code, e.zoning_treatment, e.cup_required,
    e.spacing_result, e.nearest_str_distance_ft, e.density_result,
    e.rules_version, e.checked_at as eligibility_checked_at
  from listings l
  join properties p on p.id = l.property_id
  left join v_property_eligibility e on e.property_id = p.id;

-- ───────────────────────── dashboard / refresh summaries ────────────────────
create or replace function fn_listing_summary(p_market text)
returns table (
  active int, pending int, sold int, removed int,
  screened int, green int, yellow int, red int,
  median_price numeric, price_drops int)
language sql stable as $$
  select
    count(*) filter (where status = 'active' and removed_at is null)::int,
    count(*) filter (where status = 'pending')::int,
    count(*) filter (where status = 'sold')::int,
    count(*) filter (where status = 'removed' or removed_at is not null)::int,
    count(*) filter (where classification is not null)::int,
    count(*) filter (where classification = 'GREEN')::int,
    count(*) filter (where classification = 'YELLOW')::int,
    count(*) filter (where classification = 'RED')::int,
    percentile_cont(0.5) within group (order by list_price)
      filter (where status = 'active' and list_price is not null)::numeric,
    count(*) filter (where price_drop > 0)::int
  from v_listings_enriched where market_id = p_market;
$$;

/** Properties whose eligibility is older than the current rules version. */
create or replace function fn_stale_eligibility(p_market text)
returns table (property_id bigint, rules_version text, checked_at timestamptz)
language sql stable as $$
  select v.property_id, v.rules_version, v.checked_at
    from v_property_eligibility v
    join properties pr on pr.id = v.property_id
    join jurisdictions j on j.market_id = pr.market_id
   where pr.market_id = p_market
     and v.rules_version is distinct from fn_rules_version(j.id);
$$;
